### ISSUE TITLE
[user] - [bug] Able to edit others profile

### ISSUE THREAD

**Issue by jovviee** [davidbong-05/elysium#2]
When viewing others' space and click on 'My Space' , the 'follow'/ 'unfollow' button suddenly change to 'edit profile' instead of bring the me to my space. 
When click on the 'edit profile', their username and bio can be change but when it being saved changes, the changes that is made is actually on the my profile.

**Comment by davidbong-05** [comment]
Actual problem: The user profile component is not re-rendered after clicking on 'My Space'.
Root Cause:  When using :to with Vue Router's <router-link>, it does not cause a full page reload or re-render of the entire application.
Solution: Using :href for this component.
