### ISSUE TITLE
[user]-[bug] Profile owner and other user has different count on the 'Owned Collection'

### ISSUE THREAD

**Issue by jovviee** [davidbong-05/elysium#6]
![photo_2024-06-05_11-58-05](https://github.com/davidbong-05/elysium/assets/162551307/a76fdfec-8bb7-43cb-8ec0-159dead5f7b6)
- profile view from the profile owner

![photo_2024-06-05_11-58-09](https://github.com/davidbong-05/elysium/assets/162551307/e7b9fe01-8b61-4680-8a8c-faaba19b2d5c)
- profile view from other user

**Comment by davidbong-05** [comment]
Root Cause: Was using the active user address to get collection count.
Solution: Use the profile address.

Changes: Using NFTs count instead.
